- meta: end_play
  when: setup_migration != "yes"

- name: install postgres
  include_tasks: install-postgres.yml
  when:
    - install_postgres|bool

- name: add employee sample database
  include_tasks: install-employee-sample.yml
  when:
    - install_employee_sample|bool

- name: add employee target database
  include_tasks: setup-crdb-employee.yml
  when:
    - setup_crdb_employee|bool

- name: start replicator
  include_tasks: start-replicator.yml
  when:
    - start_replicator|bool

- name: create kv workload
  include_tasks: create-kv.yml
  when:
    - create_kv|bool

- name: molt scripts
  include_tasks: molt-scripts.yml
  when:
    - molt_scripts|bool
