save_ips: true
#  WARN-this version changes really fast and aborts when specified not found
maven_version: '3.9.6'
#  this works fine but the maven version keeps changing so setting to true
install_java_maven_go: true
add_githubs: true
package_java_app: true
install_postgres: true
init_postgres: true
install_employee_sample: true
setup_crdb_employee: true
install_nodejs_typescript: true
nvm_version: "0.39.1"
node_version: "19.7.0"
add_password: true
create_der_certs: true
#  don't think is needed any longer
start_replicator: false
start_java_app: true
create_kv: true
molt_scripts: true
