save_ips: true
#  WARN-this version changes really fast and aborts when specified not found
maven_version: '3.9.6'
#  this works fine but the maven version keeps changing so setting to true
install_java_maven_go: true
install_molt_replicator: true
#  this isn't working
install_dbworkload: false
add_githubs: true
# this isn't working
install_sysbench: false
package_java_app: true
install_nodejs_typescript: true
nvm_version: "0.40.1"
node_version: "20.18.0"
create_der_certs: true
start_java_app: true
